name: Motivational Merge Comment
on:
  pull_request:
    brnches:
      - main

jobs:
  comment:
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Install Dependencies
        run: yarn install --pure-lockfile

      - name: Build Action
        run: yarn build

      - name: Run Action
        uses: ./
